### ISSUE TITLE
server.register vs server.pack.register

### ISSUE THREAD

**Issue by szkrd** [peeter-tomberg/hapi-mongodb-promises#3]
Maybe I'm doing smg wrong, but I can't even register the plugin:

```
undefined
/Users/szkrd/Projects/bitbucket/apitest/node_modules/hapi/node_modules/hoek/lib/index.js:723
    throw new Error(msgs.join(' ') || 'Unknown error');
          ^
Error: Invalid dependencies options (must be a string or an array of strings) {
  "joi": "^4.6.2",
  "mongodb": "^1.4.8",
  "when": "^3.4.3",
  "0" [1]: -- missing --
}

[1] "0" must be a string
    at Object.exports.assert (/Users/szkurdi/Projects/bitbucket/apitest/node_modules/hapi/node_modules/hoek/lib/index.js:723:11)
    at Object.exports.assert (/Users/szkurdi/Projects/bitbucket/apitest/node_modules/hapi/lib/schema.js:15:10)
    at internals.Plugin.register (/Users/szkurdi/Projects/bitbucket/apitest/node_modules/hapi/lib/plugin.js:231:16)
    at Object.<anonymous> (/Users/szkurdi/Projects/bitbucket/apitest/index.js:13:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)

```

**Comment by szkrd** [comment]
this happens with the npm package, which seems to be out of date
